package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssgSubmitMst generated by hbm2java
 */
@Entity
@Table(name="assg_submit_mst"
    ,catalog="pathshala_db"
)
public class AssgSubmitMst  implements java.io.Serializable {


     private Integer assgSubmitId;
     private Integer assgId;
     private Integer assgUserId;
     private Integer assgSubmitType;
     private String assgFileUrl;
     private String assgResponseText;
     private String assgUsername;
     private Integer assgSubmitIdHide;

    public AssgSubmitMst() {
    }

    public AssgSubmitMst(Integer assgId, Integer assgUserId, Integer assgSubmitType, String assgFileUrl, String assgResponseText, String assgUsername, Integer assgSubmitIdHide) {
       this.assgId = assgId;
       this.assgUserId = assgUserId;
       this.assgSubmitType = assgSubmitType;
       this.assgFileUrl = assgFileUrl;
       this.assgResponseText = assgResponseText;
       this.assgUsername = assgUsername;
       this.assgSubmitIdHide = assgSubmitIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_submit_id", unique=true, nullable=false)
    public Integer getAssgSubmitId() {
        return this.assgSubmitId;
    }
    
    public void setAssgSubmitId(Integer assgSubmitId) {
        this.assgSubmitId = assgSubmitId;
    }
    
    @Column(name="assg_id")
    public Integer getAssgId() {
        return this.assgId;
    }
    
    public void setAssgId(Integer assgId) {
        this.assgId = assgId;
    }
    
    @Column(name="assg_user_id")
    public Integer getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(Integer assgUserId) {
        this.assgUserId = assgUserId;
    }
    
    @Column(name="assg_submit_type")
    public Integer getAssgSubmitType() {
        return this.assgSubmitType;
    }
    
    public void setAssgSubmitType(Integer assgSubmitType) {
        this.assgSubmitType = assgSubmitType;
    }
    
    @Column(name="assg_file_url", length=200)
    public String getAssgFileUrl() {
        return this.assgFileUrl;
    }
    
    public void setAssgFileUrl(String assgFileUrl) {
        this.assgFileUrl = assgFileUrl;
    }
    
    @Column(name="assg_response_text", length=2000)
    public String getAssgResponseText() {
        return this.assgResponseText;
    }
    
    public void setAssgResponseText(String assgResponseText) {
        this.assgResponseText = assgResponseText;
    }
    
    @Column(name="assg_username", length=50)
    public String getAssgUsername() {
        return this.assgUsername;
    }
    
    public void setAssgUsername(String assgUsername) {
        this.assgUsername = assgUsername;
    }
    
    @Column(name="assg_submit_id_hide")
    public Integer getAssgSubmitIdHide() {
        return this.assgSubmitIdHide;
    }
    
    public void setAssgSubmitIdHide(Integer assgSubmitIdHide) {
        this.assgSubmitIdHide = assgSubmitIdHide;
    }




}


