package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssgGroupMst generated by hbm2java
 */
@Entity
@Table(name="assg_group_mst"
    ,catalog="pathshala_db"
)
public class AssgGroupMst  implements java.io.Serializable {


     private Integer assgGroupId;
     private Integer assgGroupDtlId;
     private String assgGroupName;
     private String assgGroupDesc;
     private Integer assgGroupOwnerId;
     private Integer assgGroupIdHide;

    public AssgGroupMst() {
    }

    public AssgGroupMst(Integer assgGroupDtlId, String assgGroupName, String assgGroupDesc, Integer assgGroupOwnerId, Integer assgGroupIdHide) {
       this.assgGroupDtlId = assgGroupDtlId;
       this.assgGroupName = assgGroupName;
       this.assgGroupDesc = assgGroupDesc;
       this.assgGroupOwnerId = assgGroupOwnerId;
       this.assgGroupIdHide = assgGroupIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_group_id", unique=true, nullable=false)
    public Integer getAssgGroupId() {
        return this.assgGroupId;
    }
    
    public void setAssgGroupId(Integer assgGroupId) {
        this.assgGroupId = assgGroupId;
    }
    
    @Column(name="assg_group_dtl_id")
    public Integer getAssgGroupDtlId() {
        return this.assgGroupDtlId;
    }
    
    public void setAssgGroupDtlId(Integer assgGroupDtlId) {
        this.assgGroupDtlId = assgGroupDtlId;
    }
    
    @Column(name="assg_group_name", length=25)
    public String getAssgGroupName() {
        return this.assgGroupName;
    }
    
    public void setAssgGroupName(String assgGroupName) {
        this.assgGroupName = assgGroupName;
    }
    
    @Column(name="assg_group_desc", length=100)
    public String getAssgGroupDesc() {
        return this.assgGroupDesc;
    }
    
    public void setAssgGroupDesc(String assgGroupDesc) {
        this.assgGroupDesc = assgGroupDesc;
    }
    
    @Column(name="assg_group_owner_id")
    public Integer getAssgGroupOwnerId() {
        return this.assgGroupOwnerId;
    }
    
    public void setAssgGroupOwnerId(Integer assgGroupOwnerId) {
        this.assgGroupOwnerId = assgGroupOwnerId;
    }
    
    @Column(name="assg_group_id_hide")
    public Integer getAssgGroupIdHide() {
        return this.assgGroupIdHide;
    }
    
    public void setAssgGroupIdHide(Integer assgGroupIdHide) {
        this.assgGroupIdHide = assgGroupIdHide;
    }




}


