package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssgGroupUser generated by hbm2java
 */
@Entity
@Table(name="assg_group_user"
    ,catalog="pathshala_db"
)
public class AssgGroupUser  implements java.io.Serializable {


     private Integer assgUsergroupId;
     private int assgGroupId;
     private int assgUserId;
     private String assgUserName;
     private Integer assgUsergroupIdHide;

    public AssgGroupUser() {
    }

	
    public AssgGroupUser(int assgGroupId, int assgUserId) {
        this.assgGroupId = assgGroupId;
        this.assgUserId = assgUserId;
    }
    public AssgGroupUser(int assgGroupId, int assgUserId, String assgUserName, Integer assgUsergroupIdHide) {
       this.assgGroupId = assgGroupId;
       this.assgUserId = assgUserId;
       this.assgUserName = assgUserName;
       this.assgUsergroupIdHide = assgUsergroupIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_usergroup_id", unique=true, nullable=false)
    public Integer getAssgUsergroupId() {
        return this.assgUsergroupId;
    }
    
    public void setAssgUsergroupId(Integer assgUsergroupId) {
        this.assgUsergroupId = assgUsergroupId;
    }
    
    @Column(name="assg_group_id", nullable=false)
    public int getAssgGroupId() {
        return this.assgGroupId;
    }
    
    public void setAssgGroupId(int assgGroupId) {
        this.assgGroupId = assgGroupId;
    }
    
    @Column(name="assg_user_id", nullable=false)
    public int getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(int assgUserId) {
        this.assgUserId = assgUserId;
    }
    
    @Column(name="assg_user_name", length=50)
    public String getAssgUserName() {
        return this.assgUserName;
    }
    
    public void setAssgUserName(String assgUserName) {
        this.assgUserName = assgUserName;
    }
    
    @Column(name="assg_usergroup_id_hide")
    public Integer getAssgUsergroupIdHide() {
        return this.assgUsergroupIdHide;
    }
    
    public void setAssgUsergroupIdHide(Integer assgUsergroupIdHide) {
        this.assgUsergroupIdHide = assgUsergroupIdHide;
    }




}


