package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssgMst generated by hbm2java
 */
@Entity
@Table(name="assg_mst"
    ,catalog="pathshala_db"
)
public class AssgMst  implements java.io.Serializable {


     private Integer assgId;
     private Integer assgOwnerId;
     private String assgTitle;
     private String assgSubject;
     private String assgDetails;
     private Integer assgDiscussionId;
     private Integer assgSubmitType;
     private Date assgSubmitDate;
     private String assgSubmissionDetails;
     private String assgFileUrl;
     private Integer assgIdHide;
     private Integer assgEvaluateIdHide;

    public AssgMst() {
    }

    public AssgMst(Integer assgOwnerId, String assgTitle, String assgSubject, String assgDetails, Integer assgDiscussionId, Integer assgSubmitType, Date assgSubmitDate, String assgSubmissionDetails, String assgFileUrl, Integer assgIdHide, Integer assgEvaluateIdHide) {
       this.assgOwnerId = assgOwnerId;
       this.assgTitle = assgTitle;
       this.assgSubject = assgSubject;
       this.assgDetails = assgDetails;
       this.assgDiscussionId = assgDiscussionId;
       this.assgSubmitType = assgSubmitType;
       this.assgSubmitDate = assgSubmitDate;
       this.assgSubmissionDetails = assgSubmissionDetails;
       this.assgFileUrl = assgFileUrl;
       this.assgIdHide = assgIdHide;
       this.assgEvaluateIdHide = assgEvaluateIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_id", unique=true, nullable=false)
    public Integer getAssgId() {
        return this.assgId;
    }
    
    public void setAssgId(Integer assgId) {
        this.assgId = assgId;
    }
    
    @Column(name="assg_owner_id")
    public Integer getAssgOwnerId() {
        return this.assgOwnerId;
    }
    
    public void setAssgOwnerId(Integer assgOwnerId) {
        this.assgOwnerId = assgOwnerId;
    }
    
    @Column(name="assg_title", length=25)
    public String getAssgTitle() {
        return this.assgTitle;
    }
    
    public void setAssgTitle(String assgTitle) {
        this.assgTitle = assgTitle;
    }
    
    @Column(name="assg_subject", length=50)
    public String getAssgSubject() {
        return this.assgSubject;
    }
    
    public void setAssgSubject(String assgSubject) {
        this.assgSubject = assgSubject;
    }
    
    @Column(name="assg_details", length=80)
    public String getAssgDetails() {
        return this.assgDetails;
    }
    
    public void setAssgDetails(String assgDetails) {
        this.assgDetails = assgDetails;
    }
    
    @Column(name="assg_discussion_id")
    public Integer getAssgDiscussionId() {
        return this.assgDiscussionId;
    }
    
    public void setAssgDiscussionId(Integer assgDiscussionId) {
        this.assgDiscussionId = assgDiscussionId;
    }
    
    @Column(name="assg_submit_type")
    public Integer getAssgSubmitType() {
        return this.assgSubmitType;
    }
    
    public void setAssgSubmitType(Integer assgSubmitType) {
        this.assgSubmitType = assgSubmitType;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="assg_submit_date", length=19)
    public Date getAssgSubmitDate() {
        return this.assgSubmitDate;
    }
    
    public void setAssgSubmitDate(Date assgSubmitDate) {
        this.assgSubmitDate = assgSubmitDate;
    }
    
    @Column(name="assg_submission_details", length=300)
    public String getAssgSubmissionDetails() {
        return this.assgSubmissionDetails;
    }
    
    public void setAssgSubmissionDetails(String assgSubmissionDetails) {
        this.assgSubmissionDetails = assgSubmissionDetails;
    }
    
    @Column(name="assg_file_url", length=300)
    public String getAssgFileUrl() {
        return this.assgFileUrl;
    }
    
    public void setAssgFileUrl(String assgFileUrl) {
        this.assgFileUrl = assgFileUrl;
    }
    
    @Column(name="assg_id_hide")
    public Integer getAssgIdHide() {
        return this.assgIdHide;
    }
    
    public void setAssgIdHide(Integer assgIdHide) {
        this.assgIdHide = assgIdHide;
    }
    
    @Column(name="assg_evaluate_id_hide")
    public Integer getAssgEvaluateIdHide() {
        return this.assgEvaluateIdHide;
    }
    
    public void setAssgEvaluateIdHide(Integer assgEvaluateIdHide) {
        this.assgEvaluateIdHide = assgEvaluateIdHide;
    }




}


