package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssgEvaluateMst generated by hbm2java
 */
@Entity
@Table(name="assg_evaluate_mst"
    ,catalog="pathshala_db"
)
public class AssgEvaluateMst  implements java.io.Serializable {


     private Integer assgEvalId;
     private Integer assgSubmitId;
     private Integer assgMstId;
     private Integer assgUserId;
     private Integer assgEvaluatedMarks;
     private Integer assgTotalMarks;
     private Integer assgRejected;
     private Integer assgCopied;
     private String assgRemarks;
     private Integer assgEvalIdHide;

    public AssgEvaluateMst() {
    }

    public AssgEvaluateMst(Integer assgSubmitId, Integer assgMstId, Integer assgUserId, Integer assgEvaluatedMarks, Integer assgTotalMarks, Integer assgRejected, Integer assgCopied, String assgRemarks, Integer assgEvalIdHide) {
       this.assgSubmitId = assgSubmitId;
       this.assgMstId = assgMstId;
       this.assgUserId = assgUserId;
       this.assgEvaluatedMarks = assgEvaluatedMarks;
       this.assgTotalMarks = assgTotalMarks;
       this.assgRejected = assgRejected;
       this.assgCopied = assgCopied;
       this.assgRemarks = assgRemarks;
       this.assgEvalIdHide = assgEvalIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_eval_id", unique=true, nullable=false)
    public Integer getAssgEvalId() {
        return this.assgEvalId;
    }
    
    public void setAssgEvalId(Integer assgEvalId) {
        this.assgEvalId = assgEvalId;
    }
    
    @Column(name="assg_submit_id")
    public Integer getAssgSubmitId() {
        return this.assgSubmitId;
    }
    
    public void setAssgSubmitId(Integer assgSubmitId) {
        this.assgSubmitId = assgSubmitId;
    }
    
    @Column(name="assg_mst_id")
    public Integer getAssgMstId() {
        return this.assgMstId;
    }
    
    public void setAssgMstId(Integer assgMstId) {
        this.assgMstId = assgMstId;
    }
    
    @Column(name="assg_user_id")
    public Integer getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(Integer assgUserId) {
        this.assgUserId = assgUserId;
    }
    
    @Column(name="assg_evaluated_marks")
    public Integer getAssgEvaluatedMarks() {
        return this.assgEvaluatedMarks;
    }
    
    public void setAssgEvaluatedMarks(Integer assgEvaluatedMarks) {
        this.assgEvaluatedMarks = assgEvaluatedMarks;
    }
    
    @Column(name="assg_total_marks")
    public Integer getAssgTotalMarks() {
        return this.assgTotalMarks;
    }
    
    public void setAssgTotalMarks(Integer assgTotalMarks) {
        this.assgTotalMarks = assgTotalMarks;
    }
    
    @Column(name="assg_rejected")
    public Integer getAssgRejected() {
        return this.assgRejected;
    }
    
    public void setAssgRejected(Integer assgRejected) {
        this.assgRejected = assgRejected;
    }
    
    @Column(name="assg_copied")
    public Integer getAssgCopied() {
        return this.assgCopied;
    }
    
    public void setAssgCopied(Integer assgCopied) {
        this.assgCopied = assgCopied;
    }
    
    @Column(name="assg_remarks", length=50)
    public String getAssgRemarks() {
        return this.assgRemarks;
    }
    
    public void setAssgRemarks(String assgRemarks) {
        this.assgRemarks = assgRemarks;
    }
    
    @Column(name="assg_eval_id_hide")
    public Integer getAssgEvalIdHide() {
        return this.assgEvalIdHide;
    }
    
    public void setAssgEvalIdHide(Integer assgEvalIdHide) {
        this.assgEvalIdHide = assgEvalIdHide;
    }




}


