package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssgDtl generated by hbm2java
 */
@Entity
@Table(name="assg_dtl"
    ,catalog="pathshala_db"
)
public class AssgDtl  implements java.io.Serializable {


     private Integer assgDtlId;
     private int assgMstId;
     private int assgGroupFlag;
     private int assgUserId;
     private Integer assgDtlIdHide;

    public AssgDtl() {
    }

	
    public AssgDtl(int assgMstId, int assgGroupFlag, int assgUserId) {
        this.assgMstId = assgMstId;
        this.assgGroupFlag = assgGroupFlag;
        this.assgUserId = assgUserId;
    }
    public AssgDtl(int assgMstId, int assgGroupFlag, int assgUserId, Integer assgDtlIdHide) {
       this.assgMstId = assgMstId;
       this.assgGroupFlag = assgGroupFlag;
       this.assgUserId = assgUserId;
       this.assgDtlIdHide = assgDtlIdHide;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assg_dtl_id", unique=true, nullable=false)
    public Integer getAssgDtlId() {
        return this.assgDtlId;
    }
    
    public void setAssgDtlId(Integer assgDtlId) {
        this.assgDtlId = assgDtlId;
    }
    
    @Column(name="assg_mst_id", nullable=false)
    public int getAssgMstId() {
        return this.assgMstId;
    }
    
    public void setAssgMstId(int assgMstId) {
        this.assgMstId = assgMstId;
    }
    
    @Column(name="assg_group_flag", nullable=false)
    public int getAssgGroupFlag() {
        return this.assgGroupFlag;
    }
    
    public void setAssgGroupFlag(int assgGroupFlag) {
        this.assgGroupFlag = assgGroupFlag;
    }
    
    @Column(name="assg_user_id", nullable=false)
    public int getAssgUserId() {
        return this.assgUserId;
    }
    
    public void setAssgUserId(int assgUserId) {
        this.assgUserId = assgUserId;
    }
    
    @Column(name="assg_dtl_id_hide")
    public Integer getAssgDtlIdHide() {
        return this.assgDtlIdHide;
    }
    
    public void setAssgDtlIdHide(Integer assgDtlIdHide) {
        this.assgDtlIdHide = assgDtlIdHide;
    }




}


