package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChatMsg generated by hbm2java
 */
@Entity
@Table(name="chat_msg"
    ,catalog="pathshala_db"
)
public class ChatMsg  implements java.io.Serializable {


     private Integer chatMsgId;
     private Integer chatUserId;
     private Integer chatPadId;
     private Integer chatPositionId;
     private String chatMsgValue;
     private Date chatMsgTime;
     private Integer chatVisible;

    public ChatMsg() {
    }

    public ChatMsg(Integer chatUserId, Integer chatPadId, Integer chatPositionId, String chatMsgValue, Date chatMsgTime, Integer chatVisible) {
       this.chatUserId = chatUserId;
       this.chatPadId = chatPadId;
       this.chatPositionId = chatPositionId;
       this.chatMsgValue = chatMsgValue;
       this.chatMsgTime = chatMsgTime;
       this.chatVisible = chatVisible;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="chat_msg_id", unique=true, nullable=false)
    public Integer getChatMsgId() {
        return this.chatMsgId;
    }
    
    public void setChatMsgId(Integer chatMsgId) {
        this.chatMsgId = chatMsgId;
    }
    
    @Column(name="chat_user_id")
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    
    @Column(name="chat_pad_id")
    public Integer getChatPadId() {
        return this.chatPadId;
    }
    
    public void setChatPadId(Integer chatPadId) {
        this.chatPadId = chatPadId;
    }
    
    @Column(name="chat_position_id")
    public Integer getChatPositionId() {
        return this.chatPositionId;
    }
    
    public void setChatPositionId(Integer chatPositionId) {
        this.chatPositionId = chatPositionId;
    }
    
    @Column(name="chat_msg_value", length=250)
    public String getChatMsgValue() {
        return this.chatMsgValue;
    }
    
    public void setChatMsgValue(String chatMsgValue) {
        this.chatMsgValue = chatMsgValue;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="chat_msg_time", length=19)
    public Date getChatMsgTime() {
        return this.chatMsgTime;
    }
    
    public void setChatMsgTime(Date chatMsgTime) {
        this.chatMsgTime = chatMsgTime;
    }
    
    @Column(name="chat_visible")
    public Integer getChatVisible() {
        return this.chatVisible;
    }
    
    public void setChatVisible(Integer chatVisible) {
        this.chatVisible = chatVisible;
    }




}


