package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChatUserVote generated by hbm2java
 */
@Entity
@Table(name="chat_user_vote"
    ,catalog="pathshala_db"
)
public class ChatUserVote  implements java.io.Serializable {


     private Integer chatVoteHisId;
     private Integer chatUserId;
     private Integer chatMsgId;
     private Integer chatVisible;

    public ChatUserVote() {
    }

    public ChatUserVote(Integer chatUserId, Integer chatMsgId, Integer chatVisible) {
       this.chatUserId = chatUserId;
       this.chatMsgId = chatMsgId;
       this.chatVisible = chatVisible;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="chat_vote_his_id", unique=true, nullable=false)
    public Integer getChatVoteHisId() {
        return this.chatVoteHisId;
    }
    
    public void setChatVoteHisId(Integer chatVoteHisId) {
        this.chatVoteHisId = chatVoteHisId;
    }
    
    @Column(name="chat_user_id")
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    
    @Column(name="chat_msg_id")
    public Integer getChatMsgId() {
        return this.chatMsgId;
    }
    
    public void setChatMsgId(Integer chatMsgId) {
        this.chatMsgId = chatMsgId;
    }
    
    @Column(name="chat_visible")
    public Integer getChatVisible() {
        return this.chatVisible;
    }
    
    public void setChatVisible(Integer chatVisible) {
        this.chatVisible = chatVisible;
    }




}


