package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChatUser generated by hbm2java
 */
@Entity
@Table(name="chat_user"
    ,catalog="pathshala_db"
)
public class ChatUser  implements java.io.Serializable {


     private Integer chatUserId;
     private String chatUserName;
     private String chatUserDesc;
     private byte[] chatUserImage;
     private Integer chatUserVotes;

    public ChatUser() {
    }

    public ChatUser(String chatUserName, String chatUserDesc, byte[] chatUserImage, Integer chatUserVotes) {
       this.chatUserName = chatUserName;
       this.chatUserDesc = chatUserDesc;
       this.chatUserImage = chatUserImage;
       this.chatUserVotes = chatUserVotes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="chat_user_id", unique=true, nullable=false)
    public Integer getChatUserId() {
        return this.chatUserId;
    }
    
    public void setChatUserId(Integer chatUserId) {
        this.chatUserId = chatUserId;
    }
    
    @Column(name="chat_user_name", length=45)
    public String getChatUserName() {
        return this.chatUserName;
    }
    
    public void setChatUserName(String chatUserName) {
        this.chatUserName = chatUserName;
    }
    
    @Column(name="chat_user_desc", length=45)
    public String getChatUserDesc() {
        return this.chatUserDesc;
    }
    
    public void setChatUserDesc(String chatUserDesc) {
        this.chatUserDesc = chatUserDesc;
    }
    
    @Column(name="chat_user_image")
    public byte[] getChatUserImage() {
        return this.chatUserImage;
    }
    
    public void setChatUserImage(byte[] chatUserImage) {
        this.chatUserImage = chatUserImage;
    }
    
    @Column(name="chat_user_votes")
    public Integer getChatUserVotes() {
        return this.chatUserVotes;
    }
    
    public void setChatUserVotes(Integer chatUserVotes) {
        this.chatUserVotes = chatUserVotes;
    }




}


