package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmnElementMst generated by hbm2java
 */
@Entity
@Table(name="cmn_element_mst"
    ,catalog="pathshala_db"
)
public class CmnElementMst  implements java.io.Serializable {


     private Long elementId;
     private String elementName;
     private String elementDesc;
     private Long parentElementId;
     private Integer elementOrder;
     private String elementUrl;
     private char activateFlag;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnElementMst() {
    }

	
    public CmnElementMst(String elementName, char activateFlag) {
        this.elementName = elementName;
        this.activateFlag = activateFlag;
    }
    public CmnElementMst(String elementName, String elementDesc, Long parentElementId, Integer elementOrder, String elementUrl, char activateFlag, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.elementName = elementName;
       this.elementDesc = elementDesc;
       this.parentElementId = parentElementId;
       this.elementOrder = elementOrder;
       this.elementUrl = elementUrl;
       this.activateFlag = activateFlag;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ELEMENT_ID", unique=true, nullable=false)
    public Long getElementId() {
        return this.elementId;
    }
    
    public void setElementId(Long elementId) {
        this.elementId = elementId;
    }
    
    @Column(name="ELEMENT_NAME", nullable=false, length=100)
    public String getElementName() {
        return this.elementName;
    }
    
    public void setElementName(String elementName) {
        this.elementName = elementName;
    }
    
    @Column(name="ELEMENT_DESC", length=130)
    public String getElementDesc() {
        return this.elementDesc;
    }
    
    public void setElementDesc(String elementDesc) {
        this.elementDesc = elementDesc;
    }
    
    @Column(name="PARENT_ELEMENT_ID")
    public Long getParentElementId() {
        return this.parentElementId;
    }
    
    public void setParentElementId(Long parentElementId) {
        this.parentElementId = parentElementId;
    }
    
    @Column(name="ELEMENT_ORDER")
    public Integer getElementOrder() {
        return this.elementOrder;
    }
    
    public void setElementOrder(Integer elementOrder) {
        this.elementOrder = elementOrder;
    }
    
    @Column(name="ELEMENT_URL", length=130)
    public String getElementUrl() {
        return this.elementUrl;
    }
    
    public void setElementUrl(String elementUrl) {
        this.elementUrl = elementUrl;
    }
    
    @Column(name="ACTIVATE_FLAG", nullable=false, length=1)
    public char getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(char activateFlag) {
        this.activateFlag = activateFlag;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATED_DATE", length=10)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


