package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmnRoleMst generated by hbm2java
 */
@Entity
@Table(name="cmn_role_mst"
    ,catalog="pathshala_db"
)
public class CmnRoleMst  implements java.io.Serializable {


     private Long roleId;
     private String roleName;
     private String roleDesc;
     private String activateFlag;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnRoleMst() {
    }

	
    public CmnRoleMst(String roleName, String roleDesc, String activateFlag) {
        this.roleName = roleName;
        this.roleDesc = roleDesc;
        this.activateFlag = activateFlag;
    }
    public CmnRoleMst(String roleName, String roleDesc, String activateFlag, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.roleName = roleName;
       this.roleDesc = roleDesc;
       this.activateFlag = activateFlag;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ROLE_ID", unique=true, nullable=false)
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="ROLE_NAME", nullable=false, length=80)
    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }
    
    @Column(name="ROLE_DESC", nullable=false, length=150)
    public String getRoleDesc() {
        return this.roleDesc;
    }
    
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }
    
    @Column(name="ACTIVATE_FLAG", nullable=false, length=1)
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATED_DATE", length=10)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


