package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CmnRoleActivationMpg generated by hbm2java
 */
@Entity
@Table(name="cmn_role_activation_mpg"
    ,catalog="pathshala_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="ACTIVATION_CODE") 
)
public class CmnRoleActivationMpg  implements java.io.Serializable {


     private Long roleActId;
     private long roleId;
     private long universityId;
     private String activationCode;
     private Date changedDate;
     private String activateFlag;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnRoleActivationMpg() {
    }

	
    public CmnRoleActivationMpg(long roleId, long universityId, String activationCode, String activateFlag) {
        this.roleId = roleId;
        this.universityId = universityId;
        this.activationCode = activationCode;
        this.activateFlag = activateFlag;
    }
    public CmnRoleActivationMpg(long roleId, long universityId, String activationCode, Date changedDate, String activateFlag, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.roleId = roleId;
       this.universityId = universityId;
       this.activationCode = activationCode;
       this.changedDate = changedDate;
       this.activateFlag = activateFlag;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ROLE_ACT_ID", unique=true, nullable=false)
    public Long getRoleActId() {
        return this.roleActId;
    }
    
    public void setRoleActId(Long roleActId) {
        this.roleActId = roleActId;
    }
    
    @Column(name="ROLE_ID", nullable=false)
    public long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="UNIVERSITY_ID", nullable=false)
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    
    @Column(name="ACTIVATION_CODE", unique=true, nullable=false, length=50)
    public String getActivationCode() {
        return this.activationCode;
    }
    
    public void setActivationCode(String activationCode) {
        this.activationCode = activationCode;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CHANGED_DATE", length=10)
    public Date getChangedDate() {
        return this.changedDate;
    }
    
    public void setChangedDate(Date changedDate) {
        this.changedDate = changedDate;
    }
    
    @Column(name="ACTIVATE_FLAG", nullable=false, length=1)
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATED_DATE", length=10)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


