package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmnRoleElementRlt generated by hbm2java
 */
@Entity
@Table(name="cmn_role_element_rlt"
    ,catalog="pathshala_db"
)
public class CmnRoleElementRlt  implements java.io.Serializable {


     private Long roleElementId;
     private Long roleId;
     private Long elementId;
     private String activateFlag;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnRoleElementRlt() {
    }

	
    public CmnRoleElementRlt(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    public CmnRoleElementRlt(Long roleId, Long elementId, String activateFlag, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.roleId = roleId;
       this.elementId = elementId;
       this.activateFlag = activateFlag;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ROLE_ELEMENT_ID", unique=true, nullable=false)
    public Long getRoleElementId() {
        return this.roleElementId;
    }
    
    public void setRoleElementId(Long roleElementId) {
        this.roleElementId = roleElementId;
    }
    
    @Column(name="ROLE_ID")
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="ELEMENT_ID")
    public Long getElementId() {
        return this.elementId;
    }
    
    public void setElementId(Long elementId) {
        this.elementId = elementId;
    }
    
    @Column(name="ACTIVATE_FLAG", nullable=false, length=1)
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DATE", length=10)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="UPDATED_DATE", length=10)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


