package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CmnUserRoleRlt generated by hbm2java
 */
@Entity
@Table(name="cmn_user_role_rlt"
    ,catalog="pathshala_db"
)
public class CmnUserRoleRlt  implements java.io.Serializable {


     private Long userRoleId;
     private long userId;
     private long roleId;
     private String activateFlag;
     private long universityId;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public CmnUserRoleRlt() {
    }

	
    public CmnUserRoleRlt(long userId, long roleId, long universityId) {
        this.userId = userId;
        this.roleId = roleId;
        this.universityId = universityId;
    }
    public CmnUserRoleRlt(long userId, long roleId, String activateFlag, long universityId, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.userId = userId;
       this.roleId = roleId;
       this.activateFlag = activateFlag;
       this.universityId = universityId;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="USER_ROLE_ID", unique=true, nullable=false)
    public Long getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }
    
    @Column(name="USER_ID", nullable=false)
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    
    @Column(name="ROLE_ID", nullable=false)
    public long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }
    
    @Column(name="ACTIVATE_FLAG", length=1)
    public String getActivateFlag() {
        return this.activateFlag;
    }
    
    public void setActivateFlag(String activateFlag) {
        this.activateFlag = activateFlag;
    }
    
    @Column(name="UNIVERSITY_ID", nullable=false)
    public long getUniversityId() {
        return this.universityId;
    }
    
    public void setUniversityId(long universityId) {
        this.universityId = universityId;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


