package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CmnUniversityMst generated by hbm2java
 */
@Entity
@Table(name="cmn_university_mst"
    ,catalog="pathshala_db"
)
public class CmnUniversityMst  implements java.io.Serializable {


     private Long unvId;
     private String unvName;

    public CmnUniversityMst() {
    }

    public CmnUniversityMst(String unvName) {
       this.unvName = unvName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="UNV_ID", unique=true, nullable=false)
    public Long getUnvId() {
        return this.unvId;
    }
    
    public void setUnvId(Long unvId) {
        this.unvId = unvId;
    }
    
    @Column(name="UNV_NAME", nullable=false, length=200)
    public String getUnvName() {
        return this.unvName;
    }
    
    public void setUnvName(String unvName) {
        this.unvName = unvName;
    }




}


