package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QzQuestions generated by hbm2java
 */
@Entity
@Table(name="qz_questions"
    ,catalog="pathshala_db"
)
public class QzQuestions  implements java.io.Serializable {


     private Integer qzQuestionId;
     private int qzQuizId;
     private int qzUserId;
     private String qzQuestion;
     private String qzOption1;
     private String qzOption2;
     private String qzOption3;
     private String qzOption4;
     private Integer qzCorrectAnswer;
     private Float qzQuestionMarks;
     private Float qzNegQuestionMarks;
     private Date qzCreatedOn;
     private String qzCreatedBy;
     private int qzStatus;

    public QzQuestions() {
    }

	
    public QzQuestions(int qzQuizId, int qzUserId, String qzQuestion, Date qzCreatedOn, String qzCreatedBy, int qzStatus) {
        this.qzQuizId = qzQuizId;
        this.qzUserId = qzUserId;
        this.qzQuestion = qzQuestion;
        this.qzCreatedOn = qzCreatedOn;
        this.qzCreatedBy = qzCreatedBy;
        this.qzStatus = qzStatus;
    }
    public QzQuestions(int qzQuizId, int qzUserId, String qzQuestion, String qzOption1, String qzOption2, String qzOption3, String qzOption4, Integer qzCorrectAnswer, Float qzQuestionMarks, Float qzNegQuestionMarks, Date qzCreatedOn, String qzCreatedBy, int qzStatus) {
       this.qzQuizId = qzQuizId;
       this.qzUserId = qzUserId;
       this.qzQuestion = qzQuestion;
       this.qzOption1 = qzOption1;
       this.qzOption2 = qzOption2;
       this.qzOption3 = qzOption3;
       this.qzOption4 = qzOption4;
       this.qzCorrectAnswer = qzCorrectAnswer;
       this.qzQuestionMarks = qzQuestionMarks;
       this.qzNegQuestionMarks = qzNegQuestionMarks;
       this.qzCreatedOn = qzCreatedOn;
       this.qzCreatedBy = qzCreatedBy;
       this.qzStatus = qzStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="qz_question_id", unique=true, nullable=false)
    public Integer getQzQuestionId() {
        return this.qzQuestionId;
    }
    
    public void setQzQuestionId(Integer qzQuestionId) {
        this.qzQuestionId = qzQuestionId;
    }
    
    @Column(name="qz_quiz_id", nullable=false)
    public int getQzQuizId() {
        return this.qzQuizId;
    }
    
    public void setQzQuizId(int qzQuizId) {
        this.qzQuizId = qzQuizId;
    }
    
    @Column(name="qz_user_id", nullable=false)
    public int getQzUserId() {
        return this.qzUserId;
    }
    
    public void setQzUserId(int qzUserId) {
        this.qzUserId = qzUserId;
    }
    
    @Column(name="qz_question", nullable=false, length=500)
    public String getQzQuestion() {
        return this.qzQuestion;
    }
    
    public void setQzQuestion(String qzQuestion) {
        this.qzQuestion = qzQuestion;
    }
    
    @Column(name="qz_option1", length=300)
    public String getQzOption1() {
        return this.qzOption1;
    }
    
    public void setQzOption1(String qzOption1) {
        this.qzOption1 = qzOption1;
    }
    
    @Column(name="qz_option2", length=300)
    public String getQzOption2() {
        return this.qzOption2;
    }
    
    public void setQzOption2(String qzOption2) {
        this.qzOption2 = qzOption2;
    }
    
    @Column(name="qz_option3", length=300)
    public String getQzOption3() {
        return this.qzOption3;
    }
    
    public void setQzOption3(String qzOption3) {
        this.qzOption3 = qzOption3;
    }
    
    @Column(name="qz_option4", length=300)
    public String getQzOption4() {
        return this.qzOption4;
    }
    
    public void setQzOption4(String qzOption4) {
        this.qzOption4 = qzOption4;
    }
    
    @Column(name="qz_correct_answer")
    public Integer getQzCorrectAnswer() {
        return this.qzCorrectAnswer;
    }
    
    public void setQzCorrectAnswer(Integer qzCorrectAnswer) {
        this.qzCorrectAnswer = qzCorrectAnswer;
    }
    
    @Column(name="qz_question_marks", precision=12, scale=0)
    public Float getQzQuestionMarks() {
        return this.qzQuestionMarks;
    }
    
    public void setQzQuestionMarks(Float qzQuestionMarks) {
        this.qzQuestionMarks = qzQuestionMarks;
    }
    
    @Column(name="qz_neg_question_marks", precision=12, scale=0)
    public Float getQzNegQuestionMarks() {
        return this.qzNegQuestionMarks;
    }
    
    public void setQzNegQuestionMarks(Float qzNegQuestionMarks) {
        this.qzNegQuestionMarks = qzNegQuestionMarks;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="qz_created_on", nullable=false, length=19)
    public Date getQzCreatedOn() {
        return this.qzCreatedOn;
    }
    
    public void setQzCreatedOn(Date qzCreatedOn) {
        this.qzCreatedOn = qzCreatedOn;
    }
    
    @Column(name="qz_created_by", nullable=false, length=100)
    public String getQzCreatedBy() {
        return this.qzCreatedBy;
    }
    
    public void setQzCreatedBy(String qzCreatedBy) {
        this.qzCreatedBy = qzCreatedBy;
    }
    
    @Column(name="qz_status", nullable=false)
    public int getQzStatus() {
        return this.qzStatus;
    }
    
    public void setQzStatus(int qzStatus) {
        this.qzStatus = qzStatus;
    }




}


