package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserEducationDtls generated by hbm2java
 */
@Entity
@Table(name="user_education_dtls"
    ,catalog="pathshala_db"
)
public class UserEducationDtls  implements java.io.Serializable {


     private Long userEducationId;
     private String schoolCollegeName;
     private String schoolCollegeCity;
     private Long schoolCollegeFromYear;
     private Long schoolCollegeToYear;
     private String specialization;
     private String graduationMasterTitle;
     private String majorSubject;
     private String otherMinorMajorSubject;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserEducationDtls() {
    }

	
    public UserEducationDtls(long createdUserId, Date createdDate) {
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserEducationDtls(String schoolCollegeName, String schoolCollegeCity, Long schoolCollegeFromYear, Long schoolCollegeToYear, String specialization, String graduationMasterTitle, String majorSubject, String otherMinorMajorSubject, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.schoolCollegeName = schoolCollegeName;
       this.schoolCollegeCity = schoolCollegeCity;
       this.schoolCollegeFromYear = schoolCollegeFromYear;
       this.schoolCollegeToYear = schoolCollegeToYear;
       this.specialization = specialization;
       this.graduationMasterTitle = graduationMasterTitle;
       this.majorSubject = majorSubject;
       this.otherMinorMajorSubject = otherMinorMajorSubject;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="USER_EDUCATION_ID", unique=true, nullable=false)
    public Long getUserEducationId() {
        return this.userEducationId;
    }
    
    public void setUserEducationId(Long userEducationId) {
        this.userEducationId = userEducationId;
    }
    
    @Column(name="SCHOOL_COLLEGE_NAME", length=200)
    public String getSchoolCollegeName() {
        return this.schoolCollegeName;
    }
    
    public void setSchoolCollegeName(String schoolCollegeName) {
        this.schoolCollegeName = schoolCollegeName;
    }
    
    @Column(name="SCHOOL_COLLEGE_CITY", length=150)
    public String getSchoolCollegeCity() {
        return this.schoolCollegeCity;
    }
    
    public void setSchoolCollegeCity(String schoolCollegeCity) {
        this.schoolCollegeCity = schoolCollegeCity;
    }
    
    @Column(name="SCHOOL_COLLEGE_FROM_YEAR")
    public Long getSchoolCollegeFromYear() {
        return this.schoolCollegeFromYear;
    }
    
    public void setSchoolCollegeFromYear(Long schoolCollegeFromYear) {
        this.schoolCollegeFromYear = schoolCollegeFromYear;
    }
    
    @Column(name="SCHOOL_COLLEGE_TO_YEAR")
    public Long getSchoolCollegeToYear() {
        return this.schoolCollegeToYear;
    }
    
    public void setSchoolCollegeToYear(Long schoolCollegeToYear) {
        this.schoolCollegeToYear = schoolCollegeToYear;
    }
    
    @Column(name="SPECIALIZATION", length=200)
    public String getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }
    
    @Column(name="GRADUATION_MASTER_TITLE", length=200)
    public String getGraduationMasterTitle() {
        return this.graduationMasterTitle;
    }
    
    public void setGraduationMasterTitle(String graduationMasterTitle) {
        this.graduationMasterTitle = graduationMasterTitle;
    }
    
    @Column(name="MAJOR_SUBJECT", length=100)
    public String getMajorSubject() {
        return this.majorSubject;
    }
    
    public void setMajorSubject(String majorSubject) {
        this.majorSubject = majorSubject;
    }
    
    @Column(name="OTHER_MINOR_MAJOR_SUBJECT", length=300)
    public String getOtherMinorMajorSubject() {
        return this.otherMinorMajorSubject;
    }
    
    public void setOtherMinorMajorSubject(String otherMinorMajorSubject) {
        this.otherMinorMajorSubject = otherMinorMajorSubject;
    }
    
    @Column(name="CREATED_USER_ID", nullable=false)
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


