package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserAchievementDtls generated by hbm2java
 */
@Entity
@Table(name="user_achievement_dtls"
    ,catalog="pathshala_db"
)
public class UserAchievementDtls  implements java.io.Serializable {


     private Long userAchievementId;
     private String achievementTitle;
     private String category;
     private String eventName;
     private String organizers;
     private String description;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserAchievementDtls() {
    }

	
    public UserAchievementDtls(String achievementTitle, long createdUserId, Date createdDate) {
        this.achievementTitle = achievementTitle;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserAchievementDtls(String achievementTitle, String category, String eventName, String organizers, String description, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.achievementTitle = achievementTitle;
       this.category = category;
       this.eventName = eventName;
       this.organizers = organizers;
       this.description = description;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="USER_ACHIEVEMENT_ID", unique=true, nullable=false)
    public Long getUserAchievementId() {
        return this.userAchievementId;
    }
    
    public void setUserAchievementId(Long userAchievementId) {
        this.userAchievementId = userAchievementId;
    }
    
    @Column(name="ACHIEVEMENT_TITLE", nullable=false, length=200)
    public String getAchievementTitle() {
        return this.achievementTitle;
    }
    
    public void setAchievementTitle(String achievementTitle) {
        this.achievementTitle = achievementTitle;
    }
    
    @Column(name="CATEGORY", length=150)
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    
    @Column(name="EVENT_NAME", length=150)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    
    @Column(name="ORGANIZERS", length=200)
    public String getOrganizers() {
        return this.organizers;
    }
    
    public void setOrganizers(String organizers) {
        this.organizers = organizers;
    }
    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="CREATED_USER_ID", nullable=false)
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


