package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserContactDtls generated by hbm2java
 */
@Entity
@Table(name="user_contact_dtls"
    ,catalog="pathshala_db"
)
public class UserContactDtls  implements java.io.Serializable {


     private Long userContactId;
     private String mobileNo;
     private String homeContactNo;
     private String workPhoneNo;
     private String universityWebmailId;
     private String personalEmailId;
     private String website;
     private String blog;
     private String permanentAddress;
     private String currentAddress;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserContactDtls() {
    }

    public UserContactDtls(String mobileNo, String homeContactNo, String workPhoneNo, String universityWebmailId, String personalEmailId, String website, String blog, String permanentAddress, String currentAddress, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.mobileNo = mobileNo;
       this.homeContactNo = homeContactNo;
       this.workPhoneNo = workPhoneNo;
       this.universityWebmailId = universityWebmailId;
       this.personalEmailId = personalEmailId;
       this.website = website;
       this.blog = blog;
       this.permanentAddress = permanentAddress;
       this.currentAddress = currentAddress;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="USER_CONTACT_ID", unique=true, nullable=false)
    public Long getUserContactId() {
        return this.userContactId;
    }
    
    public void setUserContactId(Long userContactId) {
        this.userContactId = userContactId;
    }
    
    @Column(name="MOBILE_NO", length=12)
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    
    @Column(name="HOME_CONTACT_NO", length=20)
    public String getHomeContactNo() {
        return this.homeContactNo;
    }
    
    public void setHomeContactNo(String homeContactNo) {
        this.homeContactNo = homeContactNo;
    }
    
    @Column(name="WORK_PHONE_NO", length=20)
    public String getWorkPhoneNo() {
        return this.workPhoneNo;
    }
    
    public void setWorkPhoneNo(String workPhoneNo) {
        this.workPhoneNo = workPhoneNo;
    }
    
    @Column(name="UNIVERSITY_WEBMAIL_ID", length=100)
    public String getUniversityWebmailId() {
        return this.universityWebmailId;
    }
    
    public void setUniversityWebmailId(String universityWebmailId) {
        this.universityWebmailId = universityWebmailId;
    }
    
    @Column(name="PERSONAL_EMAIL_ID", length=100)
    public String getPersonalEmailId() {
        return this.personalEmailId;
    }
    
    public void setPersonalEmailId(String personalEmailId) {
        this.personalEmailId = personalEmailId;
    }
    
    @Column(name="WEBSITE", length=120)
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    
    @Column(name="BLOG", length=120)
    public String getBlog() {
        return this.blog;
    }
    
    public void setBlog(String blog) {
        this.blog = blog;
    }
    
    @Column(name="PERMANENT_ADDRESS", length=500)
    public String getPermanentAddress() {
        return this.permanentAddress;
    }
    
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }
    
    @Column(name="CURRENT_ADDRESS", length=500)
    public String getCurrentAddress() {
        return this.currentAddress;
    }
    
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }
    
    @Column(name="CREATED_USER_ID")
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


