package hibernate;
// Generated Jul 8, 2013 10:32:10 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPersonalDtls generated by hbm2java
 */
@Entity
@Table(name="user_personal_dtls"
    ,catalog="pathshala_db"
)
public class UserPersonalDtls  implements java.io.Serializable {


     private Long personalDtlId;
     private String personName;
     private String personPhoto;
     private Date dateOfBirth;
     private String gender;
     private String primaryLangauge;
     private String secondaryLanguage;
     private String interests;
     private String currentCity;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserPersonalDtls() {
    }

	
    public UserPersonalDtls(String personName, String gender, long createdUserId, Date createdDate) {
        this.personName = personName;
        this.gender = gender;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserPersonalDtls(String personName, String personPhoto, Date dateOfBirth, String gender, String primaryLangauge, String secondaryLanguage, String interests, String currentCity, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.personName = personName;
       this.personPhoto = personPhoto;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.primaryLangauge = primaryLangauge;
       this.secondaryLanguage = secondaryLanguage;
       this.interests = interests;
       this.currentCity = currentCity;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PERSONAL_DTL_ID", unique=true, nullable=false)
    public Long getPersonalDtlId() {
        return this.personalDtlId;
    }
    
    public void setPersonalDtlId(Long personalDtlId) {
        this.personalDtlId = personalDtlId;
    }
    
    @Column(name="PERSON_NAME", nullable=false, length=300)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }
    
    @Column(name="PERSON_PHOTO", length=500)
    public String getPersonPhoto() {
        return this.personPhoto;
    }
    
    public void setPersonPhoto(String personPhoto) {
        this.personPhoto = personPhoto;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATE_OF_BIRTH", length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    
    @Column(name="GENDER", nullable=false, length=1)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    
    @Column(name="PRIMARY_LANGAUGE", length=100)
    public String getPrimaryLangauge() {
        return this.primaryLangauge;
    }
    
    public void setPrimaryLangauge(String primaryLangauge) {
        this.primaryLangauge = primaryLangauge;
    }
    
    @Column(name="SECONDARY_LANGUAGE", length=100)
    public String getSecondaryLanguage() {
        return this.secondaryLanguage;
    }
    
    public void setSecondaryLanguage(String secondaryLanguage) {
        this.secondaryLanguage = secondaryLanguage;
    }
    
    @Column(name="INTERESTS", length=800)
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    
    @Column(name="CURRENT_CITY", length=150)
    public String getCurrentCity() {
        return this.currentCity;
    }
    
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }
    
    @Column(name="CREATED_USER_ID", nullable=false)
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DATE", nullable=false, length=19)
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    
    @Column(name="UPDATED_USER_ID")
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE", length=19)
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


