/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GroupDiscussion;

import hibernate.ChatPad;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author admin
 */
public class GDAction extends org.apache.struts.action.Action {

    /* forward name="success" path="" */
    private static final String SUCCESS = "success";

    /**
     * This is the action called from the Struts framework.
     *
     * @param mapping The ActionMapping used to select this instance.
     * @param form The optional ActionForm bean for this request.
     * @param request The HTTP Request we are processing.
     * @param response The HTTP Response we are processing.
     * @throws java.lang.Exception
     * @return
     */
    @Override
    public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response)
            throws Exception {
        
        System.out.println("INSIDE execute method Of GDAction...");
        
        GDActionForm gdActionForm = (GDActionForm) form;
        
        
        gdActionForm.setChatRoomList(getChatRoomList(request));
        return mapping.findForward(SUCCESS);
    }

    private List<ChatPad> getChatRoomList(HttpServletRequest request) {
        
        
        SessionFactory factory=hibernate.HibernateUtil.getSessionFactory();
        Session session=factory.openSession();    
        
        Transaction tx=null;
    // Insert message with Pad ID 1 and User Id Generated by JavaScript ex.1
        try{
        tx=session.beginTransaction();
        Query q_chatRoomList=session.createQuery("from ChatPad C");
        List<ChatPad> chatRoomList =new ArrayList<ChatPad>(); 
        chatRoomList=(ArrayList<ChatPad>) q_chatRoomList.list();
       // request.setAttribute("chatRoomList", chatRoomList);         ------------------++++
        tx.commit();
        session.close();
        return chatRoomList;
        }catch(Exception ex){
        tx.rollback();
        session.close();
        ex.printStackTrace();
        
        }
        return null;
        
    }
}
