package user.model;
// Generated Jul 2, 2013 8:46:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserAchievementDtls generated by hbm2java
 */
public class UserAchievementDtls  implements java.io.Serializable {


     private Long userAchievementId;
     private String achievementTitle;
     private String category;
     private String eventName;
     private String organizers;
     private String description;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserAchievementDtls() {
    }

	
    public UserAchievementDtls(String achievementTitle, long createdUserId, Date createdDate) {
        this.achievementTitle = achievementTitle;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserAchievementDtls(String achievementTitle, String category, String eventName, String organizers, String description, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.achievementTitle = achievementTitle;
       this.category = category;
       this.eventName = eventName;
       this.organizers = organizers;
       this.description = description;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getUserAchievementId() {
        return this.userAchievementId;
    }
    
    public void setUserAchievementId(Long userAchievementId) {
        this.userAchievementId = userAchievementId;
    }
    public String getAchievementTitle() {
        return this.achievementTitle;
    }
    
    public void setAchievementTitle(String achievementTitle) {
        this.achievementTitle = achievementTitle;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    public String getOrganizers() {
        return this.organizers;
    }
    
    public void setOrganizers(String organizers) {
        this.organizers = organizers;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


