package user.model;
// Generated Jul 2, 2013 8:46:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserPersonalDtls generated by hbm2java
 */
public class UserPersonalDtls  implements java.io.Serializable {


     private Long personalDtlId;
     private String personName;
     private String personPhoto;
     private Date dateOfBirth;
     private String gender;
     private String primaryLangauge;
     private String secondaryLanguage;
     private String interests;
     private String currentCity;
     private long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserPersonalDtls() {
    }

	
    public UserPersonalDtls(String personName, String gender, long createdUserId, Date createdDate) {
        this.personName = personName;
        this.gender = gender;
        this.createdUserId = createdUserId;
        this.createdDate = createdDate;
    }
    public UserPersonalDtls(String personName, String personPhoto, Date dateOfBirth, String gender, String primaryLangauge, String secondaryLanguage, String interests, String currentCity, long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.personName = personName;
       this.personPhoto = personPhoto;
       this.dateOfBirth = dateOfBirth;
       this.gender = gender;
       this.primaryLangauge = primaryLangauge;
       this.secondaryLanguage = secondaryLanguage;
       this.interests = interests;
       this.currentCity = currentCity;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getPersonalDtlId() {
        return this.personalDtlId;
    }
    
    public void setPersonalDtlId(Long personalDtlId) {
        this.personalDtlId = personalDtlId;
    }
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }
    public String getPersonPhoto() {
        return this.personPhoto;
    }
    
    public void setPersonPhoto(String personPhoto) {
        this.personPhoto = personPhoto;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPrimaryLangauge() {
        return this.primaryLangauge;
    }
    
    public void setPrimaryLangauge(String primaryLangauge) {
        this.primaryLangauge = primaryLangauge;
    }
    public String getSecondaryLanguage() {
        return this.secondaryLanguage;
    }
    
    public void setSecondaryLanguage(String secondaryLanguage) {
        this.secondaryLanguage = secondaryLanguage;
    }
    public String getInterests() {
        return this.interests;
    }
    
    public void setInterests(String interests) {
        this.interests = interests;
    }
    public String getCurrentCity() {
        return this.currentCity;
    }
    
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }
    public long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


