package user.model;
// Generated Jul 2, 2013 8:46:38 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * UserContactDtls generated by hbm2java
 */
public class UserContactDtls  implements java.io.Serializable {


     private Long userContactId;
     private String mobileNo;
     private String homeContactNo;
     private String workPhoneNo;
     private String universityWebmailId;
     private String personalEmailId;
     private String website;
     private String blog;
     private String permanentAddress;
     private String currentAddress;
     private Long createdUserId;
     private Date createdDate;
     private Long updatedUserId;
     private Date updatedDate;

    public UserContactDtls() {
    }

    public UserContactDtls(String mobileNo, String homeContactNo, String workPhoneNo, String universityWebmailId, String personalEmailId, String website, String blog, String permanentAddress, String currentAddress, Long createdUserId, Date createdDate, Long updatedUserId, Date updatedDate) {
       this.mobileNo = mobileNo;
       this.homeContactNo = homeContactNo;
       this.workPhoneNo = workPhoneNo;
       this.universityWebmailId = universityWebmailId;
       this.personalEmailId = personalEmailId;
       this.website = website;
       this.blog = blog;
       this.permanentAddress = permanentAddress;
       this.currentAddress = currentAddress;
       this.createdUserId = createdUserId;
       this.createdDate = createdDate;
       this.updatedUserId = updatedUserId;
       this.updatedDate = updatedDate;
    }
   
    public Long getUserContactId() {
        return this.userContactId;
    }
    
    public void setUserContactId(Long userContactId) {
        this.userContactId = userContactId;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getHomeContactNo() {
        return this.homeContactNo;
    }
    
    public void setHomeContactNo(String homeContactNo) {
        this.homeContactNo = homeContactNo;
    }
    public String getWorkPhoneNo() {
        return this.workPhoneNo;
    }
    
    public void setWorkPhoneNo(String workPhoneNo) {
        this.workPhoneNo = workPhoneNo;
    }
    public String getUniversityWebmailId() {
        return this.universityWebmailId;
    }
    
    public void setUniversityWebmailId(String universityWebmailId) {
        this.universityWebmailId = universityWebmailId;
    }
    public String getPersonalEmailId() {
        return this.personalEmailId;
    }
    
    public void setPersonalEmailId(String personalEmailId) {
        this.personalEmailId = personalEmailId;
    }
    public String getWebsite() {
        return this.website;
    }
    
    public void setWebsite(String website) {
        this.website = website;
    }
    public String getBlog() {
        return this.blog;
    }
    
    public void setBlog(String blog) {
        this.blog = blog;
    }
    public String getPermanentAddress() {
        return this.permanentAddress;
    }
    
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }
    public String getCurrentAddress() {
        return this.currentAddress;
    }
    
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }
    public Long getCreatedUserId() {
        return this.createdUserId;
    }
    
    public void setCreatedUserId(Long createdUserId) {
        this.createdUserId = createdUserId;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
    public Long getUpdatedUserId() {
        return this.updatedUserId;
    }
    
    public void setUpdatedUserId(Long updatedUserId) {
        this.updatedUserId = updatedUserId;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }
    
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }




}


